
---
title: nanoCT-3D
---
graph TD
    subgraph sequence_stats
        count_bases:::done
    end
    subgraph sequence_transformation
        split_sequences:::missingoutput
        reverse:::done
    end

split_sequences ---> reverse
split_sequences ---> count_bases
